name: Ubuntu Bionic CI

on: [push, pull_request]

jobs:
  bionic-ci:
    runs-on: ubuntu-latest
    name: Ubuntu Bionic CI
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Bionic CI
        id: ci
        uses: ignition-tooling/ubuntu-bionic-ci-action@master
        with:
          apt-dependencies: 'pkg-config ruby-ronn uuid-dev libavcodec-dev libavdevice-dev libavformat-dev libavutil-dev libfreeimage-dev libgts-dev libswscale-dev libtinyxml2-dev libignition-cmake2-dev libignition-math6-dev'
          codecov-token: ${{ secrets.CODECOV_TOKEN }}
          script-after-make: ../.github/ci-bionic/after_make.sh
