name: Ubuntu CI

on:
  pull_request:
  push:
    branches:
      - 'ign-common[0-9]'
      - 'gz-common[0-9]'
      - 'main'

jobs:
  focal-ci:
    runs-on: ubuntu-latest
    name: Ubuntu Focal CI
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Compile and test
        id: ci
        uses: gazebo-tooling/action-gz-ci@focal
        with:
          codecov-enabled: true
  jammy-ci:
    runs-on: ubuntu-latest
    name: Ubuntu Jammy CI
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Compile and test
        id: ci
        uses: gazebo-tooling/action-gz-ci@jammy
  package-xml:
    runs-on: ubuntu-latest
    name: package.xml and CMake versions match
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check versions
        run: |
          package_xml_version=$(sed -nE 's/\s*<version>([0-9.]*)<\/version>\s*/\1/p' package.xml)
          echo "Version in package.xml: ${package_xml_version}"
          cmake_version=$(sed -nE 's/^project.*VERSION\s*([0-9.]*).*/\1/p' CMakeLists.txt)
          echo "Version in CMake: ${cmake_version}"
          [ package_xml_version = cmake_version ]
